spring.application.name=Recruitment Management System

# Server Configuration
server.port=8081

# MySQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Database Configuration
# spring.datasource.url=jdbc:h2:mem:recruitmentdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=user
# spring.datasource.password=pass
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# JWT Secret Configuration
jwt.secret.key=${JWT_SECRET}
jwt.expiration.ms=86400000

# Third-Party API Configuration
resume.parser.api.key=${RESUME_API_KEY}
resume.parser.api.url=https://api.apilayer.com/resume_parser/upload